// src/frontend/modals/ContextMenu.tsx
import { useEffect, useRef, useMemo } from "react"
import { createPortal } from "react-dom"

interface ContextMenuItem {
  label?: string
  icon?: React.ReactNode
  onClick?: () => void
  danger?: boolean
  separator?: boolean
}

interface ContextMenuProps {
  x: number
  y: number
  items: ContextMenuItem[]
  onClose: () => void
}

export function ContextMenu({ x, y, items, onClose }: ContextMenuProps) {
  const menuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose()
      }
    }

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose()
      }
    }

    document.addEventListener("mousedown", handleClickOutside)
    document.addEventListener("keydown", handleEscape)

    return () => {
      document.removeEventListener("mousedown", handleClickOutside)
      document.removeEventListener("keydown", handleEscape)
    }
  }, [onClose])

  // Adjust position to keep menu on screen
  useEffect(() => {
    if (menuRef.current) {
      const rect = menuRef.current.getBoundingClientRect()
      const viewportWidth = window.innerWidth
      const viewportHeight = window.innerHeight

      let adjustedX = x
      let adjustedY = y

      if (rect.right > viewportWidth) {
        adjustedX = viewportWidth - rect.width - 8
      }

      if (rect.bottom > viewportHeight) {
        adjustedY = viewportHeight - rect.height - 8
      }

      menuRef.current.style.left = `${adjustedX}px`
      menuRef.current.style.top = `${adjustedY}px`
    }
  }, [x, y])

  const menuContent = useMemo(() => (
    <div
      ref={menuRef}
      className="fixed z-[100] bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg overflow-hidden min-w-[180px]"
      style={{ left: x, top: y }}
    >
      {items.map((item, index) => (
        item.separator ? (
          <div key={index} className="h-px bg-[#2a2a2a] my-1 mx-2" />
        ) : (
          <button
            key={index}
            onClick={() => {
              if (item.onClick) {
                item.onClick()
              }
              onClose()
            }}
            className={`w-full flex items-center gap-3 px-3 py-2.5 text-sm transition-colors cursor-pointer ${
              item.danger
                ? "text-[#dc2626] hover:bg-[#dc2626]/10"
                : "text-[#e8e8e8] hover:bg-[#2a2a2a]"
            }`}
          >
            {item.icon && <span className="flex-shrink-0">{item.icon}</span>}
            <span>{item.label}</span>
          </button>
        )
      ))}
    </div>
  ), [x, y, items, onClose])

  return createPortal(menuContent, document.body)
}

// frontend/components/ui/ContextMenu.svelte
<script lang="ts">
  import { portal } from "../../lib/portal"
  interface ContextMenuItem {
    label?: string
    icon?: new (...args: any[]) => any
    onClick?: () => void
    danger?: boolean
    separator?: boolean
  }

  let { x, y, items, onClose }: {
    x: number
    y: number
    items: ContextMenuItem[]
    onClose: () => void
  } = $props()

  let menuEl: HTMLDivElement | undefined = $state()
  let position = $state({ x: 0, y: 0 })
  let ready = $state(false)

  $effect(() => {
    function handleClick(e: MouseEvent) {
      if (menuEl && !menuEl.contains(e.target as Node)) onClose()
    }
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }

    document.addEventListener("mousedown", handleClick)
    document.addEventListener("keydown", handleKey)
    return () => {
      document.removeEventListener("mousedown", handleClick)
      document.removeEventListener("keydown", handleKey)
    }
  })

  $effect(() => {
    if (!menuEl) return
    const maxX = window.innerWidth - menuEl.offsetWidth - 8
    const maxY = window.innerHeight - menuEl.offsetHeight - 8
    position = {
      x: Math.max(8, Math.min(x, maxX)),
      y: Math.max(8, Math.min(y, maxY)),
    }
    ready = true
  })
</script>

<div use:portal>
  <div
    bind:this={menuEl}
    role="menu"
    class="context-menu fixed z-[100]"
    class:visible={ready}
    style="left: {position.x}px; top: {position.y}px"
  >
    <div class="blur-border bg-[var(--bg-elevated)] rounded-lg overflow-hidden min-w-[180px] max-w-[280px] px-1.5 py-2 flex flex-col gap-y-0.5">
      {#each items as item}
        {#if item.separator}
          <div class="h-px bg-[var(--border-subtle)] my-1 mx-1"></div>
        {:else}
          <button
            role="menuitem"
            onclick={() => { item.onClick?.(); onClose() }}
            class="w-full flex items-center gap-2.5 px-2 py-1.5 text-[0.95rem] rounded-md transition-colors cursor-pointer select-none
              {item.danger
                ? 'text-red-400 hover:bg-red-500/10'
                : 'text-[var(--text-primary)] hover:bg-[var(--bg-hover-light)]'}"
          >
            {#if item.icon}
              <span class="flex-shrink-0 w-5 h-5 flex items-center justify-center">
                <item.icon size={17} strokeWidth={2} />
              </span>
            {:else}
              <span class="flex-shrink-0 w-5"></span>
            {/if}
            <span class="truncate">{item.label}</span>
          </button>
        {/if}
      {/each}
    </div>
  </div>
</div>

<style>
  .context-menu {
    transform-origin: top left;
    visibility: hidden;
  }

  .context-menu.visible {
    visibility: visible;
    animation: contextMenuIn 0.12s ease-out forwards;
  }

  @keyframes contextMenuIn {
    from {
      opacity: 0;
      transform: scale(0.96);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }
</style>
