// src/frontend/tabs/ModpacksTab.tsx
import { useState, useEffect, useRef } from "react"
import { invoke } from "@tauri-apps/api/core"
import { open } from '@tauri-apps/plugin-dialog'
import { Search, Download, Loader2, Package, ChevronLeft, ChevronRight, CheckCircle, AlertCircle } from "lucide-react"
import type { Instance, ModrinthSearchResult, ModrinthProject, ModrinthVersion } from "../../types"

interface ModpacksTabProps {
  instances: Instance[]
  onRefreshInstances?: () => void
  selectedVersion: string | null
  onSetSelectedVersion: (version: string | null) => void
  availableVersions: string[]
  onSetAvailableVersions: (versions: string[]) => void
  isLoadingVersions: boolean
  onSetIsLoadingVersions: (loading: boolean) => void
  onImport?: () => void
  onShowCreationToast?: (instanceName: string) => void
  scrollContainerRef?: React.RefObject<HTMLDivElement | null>
}

const YOUR_MODPACK_SLUG = "stellarmc-enhanced"
const YOUR_MODPACK_AUTHOR = "StellarMC"

export function ModpacksTab({ 
  instances, 
  onRefreshInstances,
  selectedVersion,
  onSetSelectedVersion,
  availableVersions,
  onSetAvailableVersions,
  isLoadingVersions,
  onSetIsLoadingVersions,
  onImport,
  onShowCreationToast,
  scrollContainerRef
}: ModpacksTabProps) {
  const [searchQuery, setSearchQuery] = useState("")
  const [searchResults, setSearchResults] = useState<ModrinthSearchResult | null>(null)
  const [isSearching, setIsSearching] = useState(false)
  const [currentPage, setCurrentPage] = useState(1)
  const [itemsPerPage] = useState(20)
  const searchTimeoutRef = useRef<NodeJS.Timeout | null>(null)
  
  const [installingModpacks, setInstallingModpacks] = useState<Set<string>>(new Set())
  const [installationStatus, setInstallationStatus] = useState<Record<string, 'success' | 'error'>>({})
  const [selectedVersions, setSelectedVersions] = useState<Record<string, string>>({})
  const [modpackVersions, setModpackVersions] = useState<Record<string, ModrinthVersion[]>>({})
  const [loadingVersions, setLoadingVersions] = useState<Set<string>>(new Set())
  const [modpackGalleries, setModpackGalleries] = useState<Record<string, string[]>>({})
  const [showInstalledOnly, setShowInstalledOnly] = useState(false)
  const [customModpack, setCustomModpack] = useState<ModrinthProject | null>(null)
  const [versionSearch, setVersionSearch] = useState("")

  useEffect(() => {
    if (onImport) {
      window.uploadModpackHandler = handleUploadModpack
    }
  }, [onImport])

  useEffect(() => {
    loadCustomModpack()
    loadPopularModpacks()
    loadAvailableVersions()
  }, [])

  useEffect(() => {
    if (searchTimeoutRef.current) {
      clearTimeout(searchTimeoutRef.current)
    }
    searchTimeoutRef.current = setTimeout(() => {
      setCurrentPage(1)
      handleSearch(1)
    }, 500)
    return () => {
      if (searchTimeoutRef.current) {
        clearTimeout(searchTimeoutRef.current)
      }
    }
  }, [searchQuery, selectedVersion])

  const loadCustomModpack = async () => {
    try {
      const projectDetails = await invoke<any>("get_project_details", {
        idOrSlug: YOUR_MODPACK_SLUG,
      })

      const modpackData: ModrinthProject = {
        project_id: projectDetails.id,
        slug: projectDetails.slug,
        title: projectDetails.title,
        description: projectDetails.description,
        author: YOUR_MODPACK_AUTHOR,
        icon_url: projectDetails.icon_url,
        downloads: projectDetails.downloads || 0,
        follows: 0,
        date_created: "",
        date_modified: "",
        latest_version: "",
        license: "",
        client_side: "required",
        server_side: "optional",
        project_type: "modpack",
        categories: [],
        versions: [],
        gallery: [],
        display_categories: []
      }
      
      setCustomModpack(modpackData)
      loadModpackGallery(projectDetails.id)
    } catch (error) {
      console.error("Failed to load your modpack:", error)
    }
  }

  const loadAvailableVersions = async () => {
    onSetIsLoadingVersions(true)
    try {
      const versions = await invoke<string[]>("get_modpack_game_versions")
      const stableVersions = versions.filter(version => {
        return /^1\.\d+(\.\d+)?$/.test(version)
      })
      onSetAvailableVersions(stableVersions)
    } catch (error) {
      console.error("Failed to load available versions:", error)
    } finally {
      onSetIsLoadingVersions(false)
    }
  }

  const loadPopularModpacks = async () => {
    setIsSearching(true)
    try {
      let facets = [["project_type:modpack"]]
      if (selectedVersion) {
        facets.push([`versions:${selectedVersion}`])
      }
      
      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: "",
        facets: JSON.stringify(facets),
        index: "downloads",
        offset: 0,
        limit: itemsPerPage,
      })
      setSearchResults(result)
      
      for (const modpack of result.hits) {
        loadModpackGallery(modpack.project_id)
      }
    } catch (error) {
      console.error("Failed to load popular modpacks:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const handleSearch = async (page: number = currentPage) => {
    const query = searchQuery.trim()
    setIsSearching(true)
    try {
      let facets = [["project_type:modpack"]]
      if (selectedVersion) {
        facets.push([`versions:${selectedVersion}`])
      }
      
      const offset = (page - 1) * itemsPerPage
      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: query || "",
        facets: JSON.stringify(facets),
        index: query ? "relevance" : "downloads",
        offset,
        limit: itemsPerPage,
      })
      setSearchResults(result)
      
      for (const modpack of result.hits) {
        loadModpackGallery(modpack.project_id)
      }
    } catch (error) {
      console.error("Search error:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const handlePageChange = (newPage: number) => {
    if (scrollContainerRef?.current) {
      scrollContainerRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
    window.scrollTo({ top: 0, behavior: 'smooth' })
    
    setCurrentPage(newPage)
    setTimeout(() => handleSearch(newPage), 100)
  }

  const isModpackInstalled = (modpackTitle: string): boolean => {
    if (!selectedVersion) {
      return instances.some(instance => instance.name === modpackTitle)
    }
    
    return instances.some(instance => {
      if (instance.name !== modpackTitle) return false

      let instanceMcVersion = instance.version
      if (instance.loader === "fabric") {
        const parts = instance.version.split('-')
        instanceMcVersion = parts[parts.length - 1]
      } else if (instance.loader === "forge") {
        const parts = instance.version.split('-')
        instanceMcVersion = parts[0]
      }
      
      return instanceMcVersion === selectedVersion
    })
  }

  const getFilteredModpacks = () => {
    if (!searchResults) return []
    
    const modpacks = showInstalledOnly 
      ? searchResults.hits.filter(modpack => isModpackInstalled(modpack.title))
      : searchResults.hits

    const shouldShowYourModpack = currentPage === 1 && !searchQuery.trim() && customModpack
    
    if (shouldShowYourModpack) {
      const filteredModpacks = modpacks.filter(m => m.project_id !== customModpack!.project_id)
      return [customModpack!, ...filteredModpacks]
    }
    
    return modpacks
  }

  const getPaginatedModpacks = () => {
    const filtered = getFilteredModpacks()
    if (!showInstalledOnly && !searchQuery.trim() && currentPage === 1 && customModpack) {
      return filtered.slice(0, itemsPerPage)
    }
    
    if (!showInstalledOnly) return filtered
    
    const startIndex = (currentPage - 1) * itemsPerPage
    const endIndex = startIndex + itemsPerPage
    return filtered.slice(startIndex, endIndex)
  }

  const loadModpackVersions = async (modpack: ModrinthProject) => {
    const projectId = modpack.project_id
    if (modpackVersions[projectId] || loadingVersions.has(projectId)) {
      return
    }

    setLoadingVersions(prev => new Set(prev).add(projectId))
    try {
      const versions = await invoke<ModrinthVersion[]>("get_modpack_versions", {
        idOrSlug: modpack.slug,
        gameVersion: selectedVersion,
      })
      setModpackVersions(prev => ({ ...prev, [projectId]: versions }))
      if (versions.length > 0) {
        setSelectedVersions(prev => ({ ...prev, [projectId]: versions[0].id }))
      }
    } catch (error) {
      console.error("Failed to load versions:", error)
    } finally {
      setLoadingVersions(prev => {
        const newSet = new Set(prev)
        newSet.delete(projectId)
        return newSet
      })
    }
  }

  const loadModpackGallery = async (projectId: string) => {
    try {
      const projectDetails = await invoke<any>("get_project_details", {
        idOrSlug: projectId,
      })
      
      if (projectDetails.gallery && projectDetails.gallery.length > 0) {
        const sortedGallery = projectDetails.gallery
          .map((img: any) => ({
            url: img.url || img,
            featured: img.featured || false,
            title: (img.title || '').toLowerCase(),
            description: (img.description || '').toLowerCase(),
          }))
          .sort((a: any, b: any) => {
            if (a.featured && !b.featured) return -1
            if (!a.featured && b.featured) return 1
            
            const aHasBanner = a.title.includes('banner') || a.description.includes('banner')
            const bHasBanner = b.title.includes('banner') || b.description.includes('banner')
            if (aHasBanner && !bHasBanner) return -1
            if (!aHasBanner && bHasBanner) return 1
            
            const aHasHeader = a.title.includes('header') || a.description.includes('header')
            const bHasHeader = b.title.includes('header') || b.description.includes('header')
            if (aHasHeader && !bHasHeader) return -1
            if (!aHasHeader && bHasHeader) return 1
            
            return 0
          })
          .map((img: any) => img.url)
        
        setModpackGalleries(prev => ({ ...prev, [projectId]: sortedGallery }))
      }
    } catch (error) {
      console.error(`Failed to load gallery for ${projectId}:`, error)
    }
  }

  const formatDownloads = (downloads: number): string => {
    if (downloads >= 1000000) return `${(downloads / 1000000).toFixed(1)}M`
    if (downloads >= 1000) return `${(downloads / 1000).toFixed(1)}K`
    return downloads.toString()
  }

  const handleInstallModpack = async (modpack: ModrinthProject) => {
    try {
      const projectId = modpack.project_id
      let versions = modpackVersions[projectId]

      if (!versions) {
        setLoadingVersions(prev => new Set(prev).add(projectId))
        versions = await invoke<ModrinthVersion[]>("get_modpack_versions", {
          idOrSlug: modpack.slug,
          gameVersion: selectedVersion,
        })
        setModpackVersions(prev => ({ ...prev, [projectId]: versions }))
        setLoadingVersions(prev => {
          const newSet = new Set(prev)
          newSet.delete(projectId)
          return newSet
        })
      }

      if (versions.length === 0) {
        alert("No versions available for this modpack")
        return
      }

      const versionId = selectedVersions[projectId] || versions[0].id
      const instanceName = modpack.title

      const existingInstance = instances.find(i => i.name === instanceName)
      const finalName = existingInstance ? `${instanceName}-${Date.now()}` : instanceName
      
      setInstallingModpacks(prev => new Set(prev).add(modpack.project_id))
      
      console.log("Installing modpack:", {
        slug: modpack.slug,
        instanceName: finalName,
        versionId: versionId,
        gameVersion: selectedVersion
      })
      
      if (onShowCreationToast) {
        onShowCreationToast(finalName)
      }
      
      await invoke("install_modpack", {
        modpackSlug: modpack.slug,
        instanceName: finalName,
        versionId: versionId,
        preferredGameVersion: selectedVersion,
      })
      
      setInstallationStatus(prev => ({ ...prev, [modpack.project_id]: 'success' }))

      if (onRefreshInstances) {
        setTimeout(() => {
          onRefreshInstances()
        }, 500)
      }

      setTimeout(() => {
        setInstallingModpacks(prev => {
          const newSet = new Set(prev)
          newSet.delete(modpack.project_id)
          return newSet
        })
        setInstallationStatus(prev => {
          const newStatus = { ...prev }
          delete newStatus[modpack.project_id]
          return newStatus
        })
      }, 3000)

    } catch (error) {
      console.error("Failed to install modpack:", error)
      setInstallationStatus(prev => ({ ...prev, [modpack.project_id]: 'error' }))
      
      setInstallingModpacks(prev => {
        const newSet = new Set(prev)
        newSet.delete(modpack.project_id)
        return newSet
      })

      setTimeout(() => {
        setInstallationStatus(prev => {
          const newStatus = { ...prev }
          delete newStatus[modpack.project_id]
          return newStatus
        })
      }, 5000)
    }
  }

  const handleUploadModpack = async () => {
    try {
      const selected = await open({
        multiple: false,
        filters: [{
          name: 'Modpack Files',
          extensions: ['mrpack', 'zip']
        }]
      })

      if (!selected) return

      const filePath = selected as string
      
      try {
        const modpackName = await invoke<string>("get_modpack_name_from_file", {
          filePath: filePath
        })
        
        console.log("Extracted modpack name:", modpackName)
        
        let finalName = modpackName
        const existingInstance = instances.find(
          i => i.name.toLowerCase() === modpackName.toLowerCase()
        )
        
        if (existingInstance) {
          finalName = `${modpackName}-${Date.now()}`
          console.log("Instance exists, using name:", finalName)
        }
        
        if (onShowCreationToast) {
          onShowCreationToast(finalName)
        }
        
        await invoke("install_modpack_from_file", {
          filePath: filePath,
          instanceName: finalName,
          preferredGameVersion: selectedVersion,
        })

        if (onRefreshInstances) {
          setTimeout(() => {
            onRefreshInstances()
          }, 500)
        }
        
      } catch (error) {
        console.error("Failed to import modpack:", error)
        alert(`Failed to install modpack: ${error}`)
      }
      
    } catch (error) {
      console.error("Failed to select modpack file:", error)
      alert(`Failed to select file: ${error}`)
    }
  }

  const getFilteredVersions = () => {
    let filtered = availableVersions

    if (versionSearch.trim()) {
      filtered = filtered.filter(v => 
        v.toLowerCase().includes(versionSearch.toLowerCase())
      )
    }

    return filtered
  }

  const filteredModpacks = getFilteredModpacks()
  const totalPages = showInstalledOnly 
    ? Math.ceil(filteredModpacks.length / itemsPerPage)
    : searchResults ? Math.ceil(searchResults.total_hits / itemsPerPage) : 1
  const showPagination = showInstalledOnly 
    ? filteredModpacks.length > itemsPerPage
    : searchResults && searchResults.total_hits > itemsPerPage

  return (
    <div className="max-w-7xl mx-auto flex gap-4">
      <div className="flex-1 min-w-0">
        <div className="relative mb-4">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#4a4a4a]" strokeWidth={2} />
          <input
            type="text"
            placeholder="Search modpacks..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#1a1a1a] rounded-lg pl-10 pr-4 py-2.5 text-sm text-[#e8e8e8] placeholder-[#4a4a4a] focus:outline-none focus:ring-2 focus:ring-[#2a2a2a] transition-all"
          />
          {isSearching && (
            <div className="absolute right-3 top-1/2 -translate-y-1/2">
              <Loader2 size={16} className="animate-spin text-[#16a34a]" />
            </div>
          )}
        </div>

        {searchResults && (
          <>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {getPaginatedModpacks().map((modpack) => {
                const isInstalling = installingModpacks.has(modpack.project_id)
                const status = installationStatus[modpack.project_id]
                const isLoadingVersionsForThis = loadingVersions.has(modpack.project_id)
                const gallery = modpackGalleries[modpack.project_id] || []
                const backgroundImage = gallery.length > 0 ? gallery[0] : modpack.icon_url
                const installed = isModpackInstalled(modpack.title)
                
                return (
                  <div
                    key={modpack.project_id}
                    className="relative bg-[#1a1a1a] rounded-2xl overflow-hidden transition-all group h-56"
                  >
                    <div className="absolute inset-0">
                      {backgroundImage ? (
                        <>
                          <img
                            src={backgroundImage}
                            alt={modpack.title}
                            className="w-full h-full object-cover"
                            style={{ 
                              objectPosition: 'center center'
                            }}
                          />
                          <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-black/90 to-transparent" />
                        </>
                      ) : (
                        <div className="w-full h-full bg-gradient-to-br from-[#16a34a]/20 to-[#15803d]/20 flex items-center justify-center">
                          <Package size={80} className="text-[#16a34a]/40" strokeWidth={1.5} />
                        </div>
                      )}
                    </div>

                    <div className="relative h-full flex flex-col p-4">
                      <div className="mt-auto flex items-end justify-between gap-3">
                        <div className="flex items-center gap-2.5 flex-1 min-w-0">
                          <div className="w-14 h-14 rounded-xl overflow-hidden flex-shrink-0">
                            {modpack.icon_url ? (
                              <img
                                src={modpack.icon_url}
                                alt={modpack.title}
                                className="w-full h-full object-cover"
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center">
                                <Package size={32} className="text-white/60" strokeWidth={1.5} />
                              </div>
                            )}
                          </div>
                          <div className="flex-1 min-w-0">
                            <h3 className="text-base font-bold text-white mb-0.5 truncate drop-shadow-lg">
                              {modpack.title}
                            </h3>
                            <p className="text-xs text-white/80 truncate drop-shadow-md">
                              by {modpack.author}
                            </p>
                            <p className="text-xs text-white/70 truncate drop-shadow-md mt-0.5">
                              {formatDownloads(modpack.downloads)} downloads
                            </p>
                          </div>
                        </div>

                        <button
                          onClick={() => {
                            loadModpackVersions(modpack)
                            handleInstallModpack(modpack)
                          }}
                          disabled={isInstalling || isLoadingVersionsForThis || installed}
                          className="flex-shrink-0 flex items-center justify-center transition-all cursor-pointer disabled:cursor-not-allowed"
                        >
                          {installed ? (
                            <CheckCircle size={28} className="text-green-500" strokeWidth={2} />
                          ) : status === 'success' ? (
                            <CheckCircle size={28} className="text-green-500" strokeWidth={2} />
                          ) : status === 'error' ? (
                            <AlertCircle size={28} className="text-red-500" strokeWidth={2} />
                          ) : isInstalling || isLoadingVersionsForThis ? (
                            <Loader2 size={28} className="text-white/60 animate-spin" strokeWidth={2} />
                          ) : (
                            <Download size={28} className="text-[#16a34a] hover:text-[#15803d]" strokeWidth={2} />
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>

            {showPagination && (
              <div className="flex items-center justify-center gap-2 mt-6 pb-4">
                <button
                  onClick={(e) => {
                    e.preventDefault()
                    handlePageChange(currentPage - 1)
                  }}
                  disabled={currentPage === 1}
                  className="flex items-center gap-1 px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] disabled:opacity-50 disabled:cursor-not-allowed text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                >
                  <ChevronLeft size={16} />
                  Previous
                </button>

                <div className="flex items-center gap-1">
                  {currentPage > 2 && (
                    <>
                      <button
                        onClick={(e) => {
                          e.preventDefault()
                          handlePageChange(1)
                        }}
                        className="px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                      >
                        1
                      </button>
                      {currentPage > 3 && (
                        <span className="px-2 text-[#4a4a4a]">...</span>
                      )}
                    </>
                  )}

                  {currentPage > 1 && (
                    <button
                      onClick={(e) => {
                        e.preventDefault()
                        handlePageChange(currentPage - 1)
                      }}
                      className="px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                    >
                      {currentPage - 1}
                    </button>
                  )}

                  <button
                    className="px-3 py-2 bg-[#16a34a] text-white rounded-lg text-sm font-medium"
                  >
                    {currentPage}
                  </button>

                  {currentPage < totalPages && (
                    <button
                      onClick={(e) => {
                        e.preventDefault()
                        handlePageChange(currentPage + 1)
                      }}
                      className="px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                    >
                      {currentPage + 1}
                    </button>
                  )}

                  {currentPage < totalPages - 1 && (
                    <>
                      {currentPage < totalPages - 2 && (
                        <span className="px-2 text-[#4a4a4a]">...</span>
                      )}
                      <button
                        onClick={(e) => {
                          e.preventDefault()
                          handlePageChange(totalPages)
                        }}
                        className="px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                      >
                        {totalPages}
                      </button>
                    </>
                  )}
                </div>

                <button
                  onClick={(e) => {
                    e.preventDefault()
                    handlePageChange(currentPage + 1)
                  }}
                  disabled={currentPage === totalPages}
                  className="flex items-center gap-1 px-3 py-2 bg-[#1a1a1a] hover:bg-[#1f1f1f] disabled:opacity-50 disabled:cursor-not-allowed text-[#e8e8e8] rounded-lg text-sm transition-colors cursor-pointer"
                >
                  Next
                  <ChevronRight size={16} />
                </button>
              </div>
            )}
          </>
        )}
      </div>

      <div className="w-56 flex-shrink-0">
        <div className="sticky top-4 space-y-3">
          <div className="bg-[#1a1a1a] rounded-lg overflow-hidden">
            <div className="p-3">
              <h3 className="font-semibold text-[#e8e8e8] mb-3">Versions</h3>
              {isLoadingVersions ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 size={20} className="animate-spin text-[#16a34a]" />
                </div>
              ) : availableVersions.length > 0 ? (
                <>
                  <div className="relative mb-3">
                    <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-[#4a4a4a]" strokeWidth={2} />
                    <input
                      type="text"
                      placeholder="Search..."
                      value={versionSearch}
                      onChange={(e) => setVersionSearch(e.target.value)}
                      className="w-full bg-[#0d0d0d] rounded-md pl-8 pr-3 py-2 text-sm text-[#e8e8e8] placeholder-[#4a4a4a] focus:outline-none focus:ring-1 focus:ring-[#2a2a2a] transition-all"
                    />
                  </div>

                  <div className="max-h-[300px] overflow-y-auto space-y-1">
                    {getFilteredVersions().map((version) => (
                      <button
                        key={version}
                        onClick={() => onSetSelectedVersion(version)}
                        className={`w-full text-left px-3 py-2 rounded-md text-sm transition-all cursor-pointer ${
                          selectedVersion === version
                            ? "bg-[#2a2a2a] text-white font-medium"
                            : "text-[#b0b0b0] hover:bg-[#0d0d0d] hover:text-[#e8e8e8]"
                        }`}
                      >
                        {version}
                      </button>
                    ))}
                  </div>
                </>
              ) : null}
            </div>
          </div>

          <div className="bg-[#1a1a1a] rounded-lg overflow-hidden">
            <div className="p-3">
              <button
                onClick={() => {
                  setShowInstalledOnly(!showInstalledOnly)
                  setCurrentPage(1)
                }}
                className={`w-full px-3 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer ${
                  showInstalledOnly
                    ? "bg-[#16a34a] text-white"
                    : "bg-[#0d0d0d] text-[#808080] hover:bg-[#1f1f1f] hover:text-[#e8e8e8]"
                }`}
              >
                {showInstalledOnly ? "Show All Modpacks" : "Show Installed Only"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/features/modrinth/ModpacksTab.svelte
<script lang="ts">
  import { Search, Download, Loader2, Package } from "lucide-svelte"
  import { invoke } from "@tauri-apps/api/core"
  import { untrack } from "svelte"
  import type { Snippet } from "svelte"
  import type { Instance, ModrinthSearchResult, ModrinthProject, ModrinthVersion, ModrinthProjectDetails } from "../../types"
  import { formatDownloads } from "../../lib/format"

  let {
    instances = [],
    onRefreshInstances = undefined as (() => void) | undefined,
    onShowCreationToast = undefined as ((instanceName: string) => void) | undefined,
    sourceSelector,
    modsSelector,
    hideToolbar = false,
    searchQuery = undefined as string | undefined,
    onSearchQueryChange = undefined as ((query: string) => void) | undefined,
    onViewProjectDetail = undefined as ((source: "modrinth" | "curseforge", projectId: string, slug: string, projectType: string, author?: string) => void) | undefined,
  }: {
    instances: Instance[]
    onRefreshInstances?: () => void
    onShowCreationToast?: (instanceName: string) => void
    sourceSelector?: Snippet
    modsSelector?: Snippet
    hideToolbar?: boolean
    searchQuery?: string
    onSearchQueryChange?: (query: string) => void
    onViewProjectDetail?: (source: "modrinth" | "curseforge", projectId: string, slug: string, projectType: string, author?: string) => void
  } = $props()

  const CUSTOM_MODPACK_SLUG = "stellarmc-enhanced"
  const CUSTOM_MODPACK_AUTHOR = "StellarMC"
  const ITEMS_PER_PAGE = 20

  let internalSearchQuery = $state("")
  let debounceSearchQuery = $derived(searchQuery ?? internalSearchQuery)
  let hits = $state<ModrinthProject[]>([])
  let isSearching = $state(false)
  let isLoadingMore = $state(false)
  let sentinelEl: HTMLDivElement | undefined = $state()
  let searchTimeout: ReturnType<typeof setTimeout> | undefined
  let offset = $state(0)
  let hasMore = true

  let selectedModpack = $state<ModrinthProject | null>(null)
  let modpackVersions = $state<Record<string, ModrinthVersion[]>>({})
  let loadingVersions = $state<Set<string>>(new Set())
  let installingVersions = $state<Set<string>>(new Set())
  let installationStatus = $state<Record<string, "success" | "error">>({})
  let customModpack = $state<ModrinthProject | null>(null)
  let customModpackLoaded = false
  $effect(() => {
    loadCustomModpack()
  })

  $effect(() => {
    debounceSearchQuery;
    if (searchTimeout) clearTimeout(searchTimeout)
    offset = 0
    hasMore = true
    searchTimeout = setTimeout(() => {
      fetchModpacks(0, true)
    }, untrack(() => hits.length === 0 ? 0 : 300))
    return () => clearTimeout(searchTimeout)
  })

  $effect(() => {
    if (!sentinelEl) return
    const el = sentinelEl
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !isLoadingMore && !isSearching && hasMore) {
          loadMore()
        }
      },
      { threshold: 0.1 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  })

  let displayedHits = $derived.by<ModrinthProject[]>(() => {
    const modpack = customModpack
    if (!modpack || debounceSearchQuery.trim() || (offset === 0 && hits.length === 0)) {
      return hits
    }
    const withoutCustom = hits.filter(m => m.project_id !== modpack.project_id)
    if (!debounceSearchQuery.trim()) {
      return [modpack, ...withoutCustom]
    }
    return hits
  })

  async function fetchModpacks(offsetVal: number, replace: boolean) {
    const query = debounceSearchQuery.trim()
    if (replace) isSearching = true
    else isLoadingMore = true

    try {
      const facets: string[][] = [["project_type:modpack"]]

      const result = await invoke<ModrinthSearchResult>("search_mods", {
        query: query || "",
        facets: JSON.stringify(facets),
        index: query ? "relevance" : "downloads",
        offset: offsetVal,
        limit: ITEMS_PER_PAGE,
      })

      offset = offsetVal + result.hits.length
      hasMore = offsetVal + result.hits.length < result.total_hits
      if (replace) {
        hits = result.hits
      } else {
        const ids = new Set(hits.map(h => h.project_id))
        hits = [...hits, ...result.hits.filter(h => !ids.has(h.project_id))]
      }
    } catch (error) {
      console.error("Search error:", error)
    } finally {
      if (replace) isSearching = false
      else isLoadingMore = false
    }
  }

  function loadMore() {
    if (!hasMore || isLoadingMore || isSearching) return
    fetchModpacks(offset, false)
  }

  async function loadCustomModpack() {
    if (customModpackLoaded) return
    customModpackLoaded = true
    try {
      const projectDetails = await invoke<ModrinthProjectDetails>("get_project_details", {
        idOrSlug: CUSTOM_MODPACK_SLUG,
      })
      const modpackData: ModrinthProject = {
        project_id: projectDetails.id,
        slug: projectDetails.slug,
        title: projectDetails.title,
        description: projectDetails.description,
        author: CUSTOM_MODPACK_AUTHOR,
        icon_url: projectDetails.icon_url,
        downloads: projectDetails.downloads || 0,
        follows: 0,
        date_created: "",
        date_modified: "",
        latest_version: "",
        license: "",
        client_side: "required",
        server_side: "optional",
        project_type: "modpack",
        categories: [],
        versions: [],
        gallery: [],
        display_categories: [],
      }
      customModpack = modpackData
    } catch (error) {
      console.error("Failed to load custom modpack:", error)
    }
  }

  async function handleModpackSelect(modpack: ModrinthProject) {
    selectedModpack = modpack
    const projectId = modpack.project_id
    if (!modpackVersions[projectId]) {
      loadingVersions = new Set(loadingVersions).add(projectId)
      try {
        const versions = await invoke<ModrinthVersion[]>("get_modpack_versions", {
          idOrSlug: modpack.slug,
          gameVersion: null,
        })
        modpackVersions = { ...modpackVersions, [projectId]: versions }
      } catch (error) {
        console.error("Failed to load versions:", error)
      } finally {
        const s = new Set(loadingVersions)
        s.delete(projectId)
        loadingVersions = s
      }
    }
  }

  async function handleInstallModpack(version: ModrinthVersion, modpack: ModrinthProject) {
    const instanceName = modpack.title
    const existingInstance = instances.find(i => i.name === instanceName)
    const finalName = existingInstance ? `${instanceName}-${Date.now()}` : instanceName

    installingVersions = new Set(installingVersions).add(version.id)
    if (onShowCreationToast) onShowCreationToast(finalName)

    try {
      await invoke("install_modpack", {
        modpackSlug: modpack.slug,
        instanceName: finalName,
        versionId: version.id,
        preferredGameVersion: null,
      })
      installationStatus = { ...installationStatus, [modpack.project_id]: "success" }
      if (onRefreshInstances) setTimeout(() => onRefreshInstances(), 500)
      setTimeout(() => {
        const s = new Set(installingVersions)
        s.delete(version.id)
        installingVersions = s
        const st = { ...installationStatus }
        delete st[modpack.project_id]
        installationStatus = st
      }, 3000)
    } catch (error) {
      console.error("Failed to install modpack:", error)
      installationStatus = { ...installationStatus, [modpack.project_id]: "error" }
      const s = new Set(installingVersions)
      s.delete(version.id)
      installingVersions = s
      setTimeout(() => {
        const st = { ...installationStatus }
        delete st[modpack.project_id]
        installationStatus = st
      }, 5000)
    }
  }

</script>

<div class="max-w-7xl mx-auto h-full flex flex-col">
  {#if !hideToolbar}
    <div class="sticky top-0 z-10 bg-[var(--content-bg)] pb-4 flex-shrink-0">
      <div class="flex gap-2 items-stretch">
        {#if sourceSelector}
          {@render sourceSelector()}
        {/if}
        <div class="relative flex-1 rounded-md bg-[var(--bg-tertiary)]">
          <Search size={16} class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] z-20 pointer-events-none" strokeWidth={2} />
          <input
            type="text"
            placeholder="Search modpacks..."
            value={searchQuery ?? internalSearchQuery}
            oninput={(e) => onSearchQueryChange ? onSearchQueryChange((e.target as HTMLInputElement).value) : (internalSearchQuery = (e.target as HTMLInputElement).value)}
            class="w-full bg-transparent rounded-md pl-10 pr-4 py-2.5 text-sm text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none transition-all relative z-10"
          />
          {#if isSearching}
            <div class="absolute right-3 top-1/2 -translate-y-1/2 z-20">
              <Loader2 size={16} class="animate-spin text-[#3b82f6]" />
            </div>
          {/if}
        </div>
        {#if modsSelector}
          {@render modsSelector()}
        {/if}
      </div>
    </div>
  {/if}

  <div class="flex-1 min-h-0 {hideToolbar ? '' : 'grid grid-cols-1 lg:grid-cols-3 gap-2'}">
    <div class="{hideToolbar ? '' : 'lg:col-span-2'} space-y-3 overflow-y-auto pr-2">
      {#each displayedHits as modpack (modpack.project_id)}
        <div
          class="rounded-md overflow-hidden cursor-pointer transition-all {selectedModpack?.project_id === modpack.project_id ? 'bg-[var(--bg-elevated)]' : 'bg-[var(--bg-tertiary)]'}"
          role="button"
          tabindex="0"
          onkeydown={(e) => { if (e.key === 'Enter') handleModpackSelect(modpack); }}
          onclick={() => { if (onViewProjectDetail) onViewProjectDetail("modrinth", modpack.project_id, modpack.slug, "modpack", modpack.author); handleModpackSelect(modpack); }}
        >
          <div class="flex min-h-0 relative z-0">
            {#if modpack.icon_url}
              <div class="w-24 h-24 flex items-center justify-center flex-shrink-0 rounded m-2">
                <img src={modpack.icon_url} alt={modpack.title} class="w-full h-full object-contain rounded" />
              </div>
            {:else}
              <div class="w-24 h-24 bg-gradient-to-br from-[#3b82f6]/10 to-[#60a5fa]/10 flex items-center justify-center flex-shrink-0 rounded m-2">
                <Package size={48} class="text-[#3b82f6]" />
              </div>
            {/if}
            <div class="flex-1 min-w-0 py-2 px-3 flex items-center gap-3">
              <div class="flex-1 min-w-0">
                <div class="flex items-start justify-between gap-2 mb-0">
                  <h3 class="font-semibold text-base text-[var(--text-primary)] truncate">{modpack.title}</h3>
                  <span class="text-xs text-[var(--text-muted)] whitespace-nowrap">by {modpack.author}</span>
                </div>
                <p class="text-sm text-[var(--text-muted)] line-clamp-2 mb-2">{modpack.description}</p>
                <div class="flex items-center gap-2 text-xs flex-wrap">
                  <span class="flex items-center gap-1 bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">
                    <Download size={12} />
                    {formatDownloads(modpack.downloads)}
                  </span>
                  {#each modpack.categories.slice(0, 2) as category}
                    <span class="bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">{category}</span>
                  {/each}
                </div>
              </div>
            </div>
          </div>
        </div>
      {/each}

      <div bind:this={sentinelEl} class="flex items-center justify-center py-4">
        {#if isLoadingMore}
          <Loader2 size={20} class="animate-spin text-[#3b82f6]" />
        {/if}
      </div>
    </div>

    {#if !hideToolbar && selectedModpack}
      {@const modpack = selectedModpack}
      <div class="bg-[var(--bg-tertiary)] rounded-md p-3 sticky top-0 self-start">
        <div class="flex gap-3 mb-4">
          {#if selectedModpack.icon_url}
            <img src={selectedModpack.icon_url} alt={selectedModpack.title} class="w-16 h-16 rounded" />
          {/if}
          <div class="flex-1 min-w-0">
            <h2 class="text-xl font-semibold text-[var(--text-primary)] truncate">{selectedModpack.title}</h2>
            <p class="text-sm text-[var(--text-muted)]">by {selectedModpack.author}</p>
          </div>
        </div>

        <p class="text-sm text-[var(--text-muted)] mb-4 leading-relaxed">{selectedModpack.description}</p>
        <div class="flex gap-2 mb-5 text-xs flex-wrap">
          <span class="flex items-center gap-1 bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">
            <Download size={12} />
            {formatDownloads(selectedModpack.downloads)}
          </span>
          <span class="bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--text-muted)]">{selectedModpack.follows.toLocaleString()} followers</span>
        </div>

        <div class="pt-1">
          <h3 class="font-semibold text-sm text-[var(--text-primary)] mb-3">Versions</h3>
          {#if loadingVersions.has(selectedModpack.project_id)}
            <div class="text-center py-6"><Loader2 size={20} class="animate-spin text-[#3b82f6] mx-auto" /></div>
          {:else if modpackVersions[selectedModpack.project_id]?.length > 0}
            <div class="space-y-2 max-h-[40vh] overflow-y-auto pr-1.5">
              {#each modpackVersions[selectedModpack.project_id] as version (version.id)}
                {@const installing = installingVersions.has(version.id)}
                {@const projectStatus = installationStatus[selectedModpack.project_id]}
                <div class="bg-[var(--bg-secondary)] rounded p-3 flex items-center justify-between gap-2">
                  <div class="flex-1 min-w-0">
                    <div class="text-sm font-medium text-[var(--text-primary)] truncate">{version.name}</div>
                    <div class="text-xs text-[#3a3f4b] truncate mt-0.5">{version.game_versions?.join(", ")}</div>
                  </div>
                  <button
                    onclick={() => handleInstallModpack(version, modpack)}
                    disabled={installing}
                    class="px-3 py-2 bg-[#3b82f6] hover:bg-[#60a5fa] disabled:opacity-50 disabled:cursor-not-allowed text-white rounded text-xs font-medium whitespace-nowrap transition-all cursor-pointer flex items-center gap-1"
                  >
                    {#if installing}
                      <Loader2 size={14} class="animate-spin" />
                    {:else if projectStatus === "success"}
                      Installed
                    {:else if projectStatus === "error"}
                      Error
                    {:else}
                      <Download size={14} />Install
                    {/if}
                  </button>
                </div>
              {/each}
            </div>
          {:else}
            <p class="text-sm text-[#3a3f4b] text-center py-3">No versions available</p>
          {/if}
        </div>
      </div>
    {/if}
  </div>
</div>
